on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          install.packages("http://www.omegahat.net/R/bin/windows/contrib/3.5.1/RDCOMClient_0.93-0.zip", repos = NULL, type = "binary")
          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
          remotes::install_deps(dependencies = c("Depends", "Imports"))
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
